name: Django CI with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Create .env file
        run: |
          echo "DEBUG=1" > .env
          echo "SECRET_KEY=temporarykey" >> .env
          echo "DJANGO_ALLOWED_HOSTS=*" >> .env
          echo "DATABASE_URL=postgres://postgres@db:5432/postgres" >> .env

      - name: Start Docker Compose services
        run: docker compose up -d

      - name: Wait for DB to be ready
        run: |
          echo "Waiting for PostgreSQL to start..."
          sleep 10

      - name: Run Django migrations
        run: docker compose exec web python /code/manage.py migrate

      - name: Run Django tests
        run: docker compose exec web python /code/manage.py test

      - name: Stop Docker Compose
        if: always()
        run: docker compose down
