name: Django CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.24-dind

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Wait for web service to be healthy
        run: |
          for i in {1..10}; do
            STATUS=$(docker inspect --format='{{json .State.Health.Status}}' $(docker compose ps -q web))
            echo "Health status: $STATUS"
            if [ "$STATUS" = "\"healthy\"" ]; then
              echo "Web container is healthy"
              break
            fi
            echo "Waiting for container to be healthy..."
            sleep 5
          done

      - name: Run Django tests
        run: docker compose exec web python manage.py test
