name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Start Docker Compose in detached mode
        run: docker compose up -d --build

      - name: Wait for web service to be healthy
        run: |
          echo "Waiting for 'web' container to be healthy..."
          for i in {1..30}; do
            status=$(docker inspect --format='{{.State.Health.Status}}' $(docker compose ps -q web) || echo "notfound")
            echo "Status: $status"
            if [ "$status" = "healthy" ]; then
              break
            fi
            sleep 3
          done

      - name: Run Django Tests
        run: docker compose exec web python manage.py test

      - name: Shut down Docker Compose
        if: always()
        run: docker compose down
